# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
  only:
  - branches

# Builds frontend
build-frontend:
  stage: build
  script:
    - cd eatseasy
    - npm install
    - npm run build
  only:
    - branches

# Build Backend
build-backend:
  stage: build
  script:
    - cd backend
    - npm install
    - node index.js
  only:
    - branches

# TODO: Once unit testing goes in then we need to add unit tests going off as well