sync_to_github:
  stage: sync
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual # Optional: Set to "manual" if you want to trigger it manually
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.name "GitLab CI/CD"
    - git config --global user.email "gitlab@example.com"

    # Clone the GitHub repository (eatseasybackend) into a temporary directory
    - git clone https://$GITHUB_TOKEN@github.com/Daniyal-Shahid/eatseasybackend.git backend-temp

    # Copy the backend folder from the GitLab repository to the temporary directory
    - cp -r backend/* backend-temp/

    # Navigate to the temporary directory
    - cd backend-temp

    # Add, commit, and push the changes to GitHub
    - git add .
    - git commit -m "Update backend folder from GitLab pipeline"
    - git push origin main

    # Clean up
    - cd ..
    - rm -rf backend-temp