stages:
  - build

# Builds frontend
build-frontend:
  image: node:20
  stage: build
  script:
    - cd eatseasy
    - npm install
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"' 

# Build Backend
build-backend:
  image: node:20  
  stage: build
  script:
    - cd backend
    - npm install
    - node index.js &  
    - sleep 5
    - if ! curl --silent http://localhost:8000 | grep "Backend running on http://localhost:8000"; then exit 1; fi
    - pkill -f "node index.js"  
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"' 