include:
  - template: Dependency-Scanning.gitlab-ci.yml

stages:
  - test

# Frontend unit tests
test-frontend:
  image: node:20
  stage: test
  script:
    - cd eatseasy
    - npm install
    - npm test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"' 

# Backend unit tests
test-backend:
  image: node:20
  stage: test
  variables:
    SPOONACULAR_API_KEY: ${SPOONACULAR_API_KEY}
    JWT_SECRET: ${JWT_SECRET}
  script:
    - cd backend
    - npm install
    - npm test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"' 

# Dependency scanning (frontend)
dependency-scanning-frontend:
  extends: gemnasium-dependency_scanning 
  variables:
    DS_TARGET_PATH: "eatseasy"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"' 

# Dependency scanning (backend)
dependency-scanning-backend:
  extends: gemnasium-dependency_scanning
  variables:
    DS_TARGET_PATH: "backend"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"' 