sync_to_github:
  stage: sync
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual # Optional: Set to "manual" if you want to trigger it manually
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.name "GitLab CI/CD"
    - git config --global user.email "gitlab@example.com"
    - git remote add github https://$GITHUB_TOKEN@github.com/Daniyal-Shahid/eatseasybackend.git || git remote set-url github https://$GITHUB_TOKEN@github.com/Daniyal-Shahid/eatseasybackend.git
    - git fetch github main
    - git checkout main
    - git rebase github/main || git merge github/main # Sync with remote
    - git push github main